In [181]:
%pip install -q nfl-data-py

import pandas as pd
import numpy as np
import nfl_data_py as nfl

WARNING: You are using pip version 21.2.4; however, version 25.2 is available.
You should consider upgrading via the '/Library/Developer/CommandLineTools/usr/bin/python3 -m pip install --upgrade pip' command.
Note: you may need to restart the kernel to use updated packages.

In [182]:
from datetime import datetime

# Set the season to analyze (e.g., 2024). Change if needed.
season = 2025
week = 1

# Load play-by-play data for the chosen season
pbp = nfl.import_pbp_data(years=[2025])

# Filter for regular season, Week 1
week_pbp = pbp[(pbp['week'] == week)]

# Keep only touchdown plays
week_tds = week_pbp[week_pbp['touchdown'] == 1]

# Count TDs per scorer. Prefer id+name if both available, else fall back to name only
use_cols = [c for c in ['td_player_id', 'td_player_name'] if c in week_tds.columns]
if use_cols:
    scorers = (
        week_tds.dropna(subset=use_cols)
        .groupby(use_cols)
        .size()
        .reset_index(name='tds')
    )
    if 'td_player_id' in use_cols:
        scorers = scorers.rename(columns={'td_player_name': 'player', 'td_player_id': 'player_id'})
    else:
        scorers = scorers.rename(columns={'td_player_name': 'player'})
else:
    # Fallback if td_* columns not present; derive from rusher/receiver
    rush = week_tds.dropna(subset=['rusher_player_id'])[['rusher_player_id', 'rusher_player_name']]
    rec = week_tds.dropna(subset=['receiver_player_id'])[['receiver_player_id', 'receiver_player_name']]
    rush.columns = ['player_id', 'player']
    rec.columns = ['player_id', 'player']
    both = pd.concat([rush, rec], ignore_index=True)
    scorers = both.groupby(['player_id', 'player']).size().reset_index(name='tds')

# Show results
scorers.head(50)

2025 done.
Downcasting floats.

     player_id        player  tds
0   00-0030061        Z.Ertz    1
1   00-0030279       K.Allen    1
2   00-0030506       T.Kelce    1
3   00-0030564     D.Hopkins    1
4   00-0032764       D.Henry    2
5   00-0033288      G.Kittle    1
6   00-0033293       A.Jones    1
7   00-0033553      J.Conner    1
8   00-0033858       J.Smith    1
9   00-0033873     P.Mahomes    1
10  00-0033906      A.Kamara    1
11  00-0034348      C.Sutton    1
12  00-0034796     L.Jackson    1
13  00-0034844     S.Barkley    1
14  00-0034857       J.Allen    2
15  00-0035644        N.Fant    1
16  00-0035700      J.Jacobs    1
17  00-0035710       D.Jones    2
18  00-0035719      D.Samuel    1
19  00-0036158     J.Dobbins    1
20  00-0036252     M.Pittman    1
21  00-0036322   J.Jefferson    1
22  00-0036389       J.Hurts    2
23  00-0036555     C.Hubbard    1
24  00-0036862   B.Skowronek    1
25  00-0036945      J.Fields    2
26  00-0036986      N.Wright    1
27  00-0036997    J.Williams    2
28  00-0037004        H.Long    1
29  00-0037112      J.Tonges    1
30  00-0037228      J.Warren    1
31  00-0037248        J.Cook    1
32  00-0037740      G.Wilson    1
33  00-0037837      C.Austin    1
34  00-0037840    K.Williams    1
35  00-0038542    B.Robinson    1
36  00-0038544    Q.Johnston    2
37  00-0038563      T.Tucker    1
38  00-0038597       C.Brown    1
39  00-0038621     D.Douglas    1
40  00-0038933     D.Kincaid    1
41  00-0038979     C.Tillman    1
42  00-0038996       T.Kraft    1
43  00-0039040      D.Achane    1
44  00-0039064     Z.Flowers    1
45  00-0039074       D.Allen    1
46  00-0039146        J.Reed    1
47  00-0039165  Z.Charbonnet    1
48  00-0039361      B.Irving    1
49  00-0039794       B.Allen    1

In [183]:
predictions = pd.read_csv(f'data/predictions_week_{week}.csv')

#Keep only player_id, player_display_name, predicted_touchdown_probability, and model_edge
predictions = predictions[['player_id', 'player_display_name', 'position','team', 'predicted_touchdown_probability', 'price', 'model_edge','market_implied_prob']]

#Sort by predicted_touchdown_probability in descending order
predictions = predictions.sort_values(by='predicted_touchdown_probability', ascending=False)

#Show the top 50 players
predictions.head(50)

,player_id,player_display_name,position,team,predicted_touchdown_probability,price,model_edge,market_implied_prob
0,00-0032764,Derrick Henry,RB,BAL,0.610808,-145.0,0.018972,0.591837
1,00-0039361,Bucky Irving,RB,TB,0.597314,-140.0,0.013981,0.583333
2,00-0039040,De'Von Achane,RB,MIA,0.574486,-140.0,-0.008847,0.583333
3,00-0034844,Saquon Barkley,RB,PHI,0.573298,-185.0,-0.075825,0.649123
4,00-0035700,Josh Jacobs,RB,GB,0.570906,-160.0,-0.044478,0.615385
5,00-0033553,James Conner,RB,ARI,0.570442,-155.0,-0.037401,0.607843
6,00-0036555,Chuba Hubbard,RB,CAR,0.548293,-105.0,0.036098,0.512195
7,00-0037840,Kyren Williams,RB,LA,0.548109,-140.0,-0.035224,0.583333
8,00-0039139,Jahmyr Gibbs,RB,DET,0.547903,-105.0,0.035707,0.512195
9,00-0038597,Chase Brown,RB,CIN,0.547071,-150.0,-0.052929,0.600000
10,00-0038542,Bijan Robinson,RB,ATL,0.545828,-175.0,-0.090536,0.636364
11,00-0036223,Jonathan Taylor,RB,IND,0.540143,-180.0,-0.102714,0.642857
12,00-0036912,DeVonta Smith,WR,PHI,0.539514,180.0,0.182371,0.357143
13,00-0036900,Ja'Marr Chase,WR,CIN,0.536732,-130.0,-0.028486,0.565217
14,00-0037248,James Cook,RB,BUF,0.528006,105.0,0.040201,0.487805
15,00-0039893,Brian Thomas Jr.,WR,JAX,0.518793,130.0,0.084011,0.434783
16,00-0031408,Mike Evans,WR,TB,0.515207,110.0,0.039016,0.476190
17,00-0036158,J.K. Dobbins,RB,DEN,0.514653,160.0,0.130037,0.384615
18,00-0035676,A.J. Brown,WR,PHI,0.503039,160.0,0.118423,0.384615
19,00-0035659,Terry McLaurin,WR,WAS,0.503017,130.0,0.068234,0.434783
20,00-0033293,Aaron Jones,RB,MIN,0.482696,165.0,0.105338,0.377358
21,00-0037744,Trey McBride,TE,ARI,0.482534,200.0,0.149201,0.333333
22,00-0039075,Puka Nacua,WR,LA,0.481319,140.0,0.064652,0.416667
23,00-0034348,Courtland Sutton,WR,DEN,0.478425,135.0,0.052893,0.425532
24,00-0030506,Travis Kelce,TE,KC,0.472411,165.0,0.095053,0.377358
25,00-0034857,Josh Allen,QB,BUF,0.471089,-120.0,-0.074365,0.545455
26,00-0034960,Jakobi Meyers,WR,LV,0.466541,225.0,0.158849,0.307692
27,00-0038544,Quentin Johnston,WR,LAC,0.466127,370.0,0.253361,0.212766
28,00-0039337,Malik Nabers,WR,NYG,0.465586,150.0,0.065586,0.400000
29,00-0034827,DJ Moore,WR,CHI,0.465005,195.0,0.126022,0.338983
30,00-0031381,Davante Adams,WR,LA,0.463883,145.0,0.055720,0.408163
31,00-0037238,Drake London,WR,ATL,0.455290,125.0,0.010846,0.444444
32,00-0038120,Breece Hall,RB,NYJ,0.451610,170.0,0.081240,0.370370
33,00-0036252,Michael Pittman,WR,IND,0.446195,215.0,0.128735,0.317460
34,00-0036389,Jalen Hurts,QB,PHI,0.441697,-150.0,-0.158303,0.600000
35,00-0033885,David Njoku,TE,CLE,0.436788,230.0,0.133757,0.303030
36,00-0033858,Jonnu Smith,TE,PIT,0.434329,400.0,0.234329,0.200000
37,00-0033280,Christian McCaffrey,RB,SF,0.432416,-155.0,-0.175427,0.607843
38,00-0036139,Rico Dowdle,RB,CAR,0.430344,320.0,0.192249,0.238095
39,00-0036407,Jerry Jeudy,WR,CLE,0.428382,200.0,0.095049,0.333333
40,00-0036275,D'Andre Swift,RB,CHI,0.427161,170.0,0.056791,0.370370
41,00-0039894,Xavier Worthy,WR,KC,0.427111,125.0,-0.017333,0.444444
42,00-0039901,Keon Coleman,WR,BUF,0.422113,210.0,0.099532,0.322581
43,00-0034753,Mark Andrews,TE,BAL,0.421154,205.0,0.093285,0.327869
44,00-0037816,Romeo Doubs,WR,GB,0.410896,230.0,0.107865,0.303030
45,00-0038134,Kenneth Walker III,RB,SEA,0.407121,120.0,-0.047425,0.454545
46,00-0036894,Pat Freiermuth,TE,PIT,0.405808,425.0,0.215332,0.190476
47,00-0039849,Marvin Harrison Jr.,WR,ARI,0.403806,150.0,0.003806,0.400000
48,00-0038117,Wan'Dale Robinson,WR,NYG,0.403713,400.0,0.203713,0.200000
49,00-0033906,Alvin Kamara,RB,NO,0.401120,-105.0,-0.111075,0.512195

In [184]:
# Join predictions with scorers: prefer player_id, else fall back to name
if 'player_id' in scorers.columns:
    pred_scored = predictions.merge(
        scorers[['player_id', 'tds']], on='player_id', how='inner'
    )
else:
    pred_scored = predictions.merge(
        scorers[['player', 'tds']], left_on='player_display_name', right_on='player', how='inner'
    )

pred_scored.sort_values(['predicted_touchdown_probability'], ascending=[False])

,player_id,player_display_name,position,team,predicted_touchdown_probability,price,model_edge,market_implied_prob,tds
0,00-0032764,Derrick Henry,RB,BAL,0.610808,-145.0,0.018972,0.591837,2
1,00-0039361,Bucky Irving,RB,TB,0.597314,-140.0,0.013981,0.583333,1
2,00-0039040,De'Von Achane,RB,MIA,0.574486,-140.0,-0.008847,0.583333,1
3,00-0034844,Saquon Barkley,RB,PHI,0.573298,-185.0,-0.075825,0.649123,1
4,00-0035700,Josh Jacobs,RB,GB,0.570906,-160.0,-0.044478,0.615385,1
5,00-0033553,James Conner,RB,ARI,0.570442,-155.0,-0.037401,0.607843,1
6,00-0036555,Chuba Hubbard,RB,CAR,0.548293,-105.0,0.036098,0.512195,1
7,00-0037840,Kyren Williams,RB,LA,0.548109,-140.0,-0.035224,0.583333,1
8,00-0038597,Chase Brown,RB,CIN,0.547071,-150.0,-0.052929,0.600000,1
9,00-0038542,Bijan Robinson,RB,ATL,0.545828,-175.0,-0.090536,0.636364,1
10,00-0037248,James Cook,RB,BUF,0.528006,105.0,0.040201,0.487805,1
11,00-0039893,Brian Thomas Jr.,WR,JAX,0.518793,130.0,0.084011,0.434783,1
12,00-0036158,J.K. Dobbins,RB,DEN,0.514653,160.0,0.130037,0.384615,1
13,00-0033293,Aaron Jones,RB,MIN,0.482696,165.0,0.105338,0.377358,1
14,00-0034348,Courtland Sutton,WR,DEN,0.478425,135.0,0.052893,0.425532,1
15,00-0030506,Travis Kelce,TE,KC,0.472411,165.0,0.095053,0.377358,1
16,00-0034857,Josh Allen,QB,BUF,0.471089,-120.0,-0.074365,0.545455,2
17,00-0038544,Quentin Johnston,WR,LAC,0.466127,370.0,0.253361,0.212766,2
18,00-0036252,Michael Pittman,WR,IND,0.446195,215.0,0.128735,0.317460,1
19,00-0036389,Jalen Hurts,QB,PHI,0.441697,-150.0,-0.158303,0.600000,2
20,00-0033858,Jonnu Smith,TE,PIT,0.434329,400.0,0.234329,0.200000,1
21,00-0039901,Keon Coleman,WR,BUF,0.422113,210.0,0.099532,0.322581,1
22,00-0039849,Marvin Harrison Jr.,WR,ARI,0.403806,150.0,0.003806,0.400000,1
23,00-0033906,Alvin Kamara,RB,NO,0.401120,-105.0,-0.111075,0.512195,1
24,00-0036322,Justin Jefferson,WR,MIN,0.400235,135.0,-0.025297,0.425532,1
25,00-0034796,Lamar Jackson,QB,BAL,0.387036,205.0,0.059168,0.327869,1
26,00-0039165,Zach Charbonnet,RB,SEA,0.385771,370.0,0.173005,0.212766,1
27,00-0035710,Daniel Jones,QB,IND,0.381421,190.0,0.036594,0.344828,2
28,00-0030061,Zach Ertz,TE,WAS,0.365058,200.0,0.031725,0.333333,1
29,00-0038996,Tucker Kraft,TE,GB,0.350923,215.0,0.033463,0.317460,1
30,00-0035644,Noah Fant,TE,CIN,0.335109,700.0,0.210109,0.125000,1
31,00-0037228,Jaylen Warren,RB,PIT,0.315350,165.0,-0.062008,0.377358,1
32,00-0038979,Cedric Tillman,WR,CLE,0.282102,280.0,0.018944,0.263158,1
33,00-0037740,Garrett Wilson,WR,NYJ,0.268982,220.0,-0.043518,0.312500,1
34,00-0038621,DeMario Douglas,WR,NE,0.263193,340.0,0.035921,0.227273,1
35,00-0030279,Keenan Allen,WR,LAC,0.229463,275.0,-0.037204,0.266667,1
36,00-0030564,DeAndre Hopkins,WR,BAL,0.213044,425.0,0.022567,0.190476,1
37,00-0036945,Justin Fields,QB,NYJ,0.207922,200.0,-0.125411,0.333333,2
38,00-0038563,Tre Tucker,WR,LV,0.206806,450.0,0.024987,0.181818,1
39,00-0036997,Javonte Williams,RB,DAL,0.204324,225.0,-0.103368,0.307692,2
40,00-0033873,Patrick Mahomes,QB,KC,0.196307,550.0,0.042461,0.153846,1
41,00-0040122,Ashton Jeanty,RB,LV,0.189891,-120.0,-0.355564,0.545455,1
42,00-0039146,Jayden Reed,WR,GB,0.179271,230.0,-0.123760,0.303030,1
43,00-0039918,Caleb Williams,QB,CHI,0.168816,650.0,0.035482,0.133333,1
44,00-0033288,George Kittle,TE,SF,0.168736,150.0,-0.231264,0.400000,1
45,00-0039794,Braelon Allen,RB,NYJ,0.165631,250.0,-0.120083,0.285714,1
46,00-0039923,J.J. McCarthy,QB,MIN,0.161650,600.0,0.018793,0.142857,1
47,00-0038933,Dalton Kincaid,TE,BUF,0.155861,350.0,-0.066361,0.222222,1
48,00-0039919,Rome Odunze,WR,CHI,0.150128,215.0,-0.167332,0.317460,1
49,00-0039917,Michael Penix Jr.,QB,ATL,0.145085,800.0,0.033974,0.111111,1
50,00-0040242,Jacory Croskey-Merritt,RB,WAS,0.131850,330.0,-0.100708,0.232558,1
51,00-0037004,Hunter Long,TE,JAX,0.121004,1200.0,0.044081,0.076923,1
52,00-0039064,Zay Flowers,WR,BAL,0.120727,200.0,-0.212606,0.333333,1
53,00-0036862,Ben Skowronek,WR,PIT,0.105680,1300.0,0.034252,0.071429,1
54,00-0037112,Jake Tonges,TE,SF,0.090624,1700.0,0.035068,0.055556,1
55,00-0035719,Deebo Samuel Sr.,WR,WAS,0.086342,195.0,-0.252641,0.338983,1
56,00-0039074,Davis Allen,TE,LA,0.085280,1700.0,0.029724,0.055556,1
57,00-0037837,Calvin Austin III,WR,PIT,0.078325,400.0,-0.121675,0.200000,1
58,00-0040129,Emeka Egbuka,WR,TB,0.058078,185.0,-0.292799,0.350877,2
59,00-0040669,Isaac TeSlaa,WR,DET,0.058064,450.0,-0.123754,0.181818,1

In [185]:
###Simulate betting on the top 10 running backs
def simulate_betting(df, scorers):
    stake = 10.0

    bets = df.copy()

    # Merge to mark hits
    bets = bets.merge(
        scorers[['player_id', 'tds']], on='player_id', how='left'
    )
    bets['tds'] = bets['tds'].fillna(0).astype(int)
    bets['hit'] = bets['tds'] > 0

    # American odds payout logic
    # profit_if_win = stake * (odds/100) if odds > 0 else stake * (100/abs(odds))
    # profit_if_loss = -stake
    is_plus = bets['price'] > 0
    profit_if_win = stake * (bets['price'] / 100.0)
    profit_if_win = profit_if_win.where(is_plus, stake * (100.0 / bets['price'].abs()))

    bets['profit'] = np.where(bets['hit'], profit_if_win, -stake)

    # Add total return
    bets['return'] = stake + bets['profit']

    # Summary metrics
    num_bets = len(bets)
    hits = int(bets['hit'].sum())
    hit_rate = hits / num_bets if num_bets else 0.0
    total_profit = float(bets['profit'].sum())
    roi = total_profit / (stake * num_bets) if num_bets else 0.0

    summary = {
        'bets': num_bets,
        'hits': hits,
        'hit_rate': round(hit_rate, 3),
        'total_profit': round(total_profit, 2),
        'roi': round(roi, 3)
    }

    display(summary)

    # Show detailed results
    cols = [
        'player_id', 'player_display_name', 'team', 'position', 'price',
        'predicted_touchdown_probability', 'model_edge', 'tds', 'hit', 'profit', 'return'
    ]
    return bets[cols].sort_values(['predicted_touchdown_probability'], ascending=[False]).reset_index(drop=True)

In [186]:
# output players from predictions that play for 'PHI', 'KC', 'LAC' or 'DAL'

#find players with model_edge > 0 and price < 500
ev = predictions[predictions['model_edge'] > 0.10] 
ev = ev[ev['price'] < 500]

#sort by model_edge in descending order
ev = ev.sort_values('model_edge', ascending=False)
ev

,player_id,player_display_name,position,team,predicted_touchdown_probability,price,model_edge,market_implied_prob
27,00-0038544,Quentin Johnston,WR,LAC,0.466127,370.0,0.253361,0.212766
36,00-0033858,Jonnu Smith,TE,PIT,0.434329,400.0,0.234329,0.200000
46,00-0036894,Pat Freiermuth,TE,PIT,0.405808,425.0,0.215332,0.190476
48,00-0038117,Wan'Dale Robinson,WR,NYG,0.403713,400.0,0.203713,0.200000
38,00-0036139,Rico Dowdle,RB,CAR,0.430344,320.0,0.192249,0.238095
12,00-0036912,DeVonta Smith,WR,PHI,0.539514,180.0,0.182371,0.357143
58,00-0039165,Zach Charbonnet,RB,SEA,0.385771,370.0,0.173005,0.212766
26,00-0034960,Jakobi Meyers,WR,LV,0.466541,225.0,0.158849,0.307692
21,00-0037744,Trey McBride,TE,ARI,0.482534,200.0,0.149201,0.333333
35,00-0033885,David Njoku,TE,CLE,0.436788,230.0,0.133757,0.303030
17,00-0036158,J.K. Dobbins,RB,DEN,0.514653,160.0,0.130037,0.384615
33,00-0036252,Michael Pittman,WR,IND,0.446195,215.0,0.128735,0.317460
29,00-0034827,DJ Moore,WR,CHI,0.465005,195.0,0.126022,0.338983
67,00-0037256,Rachaad White,RB,TB,0.361963,320.0,0.123868,0.238095
18,00-0035676,A.J. Brown,WR,PHI,0.503039,160.0,0.118423,0.384615
56,00-0038997,Josh Downs,WR,IND,0.386269,270.0,0.115998,0.270270
44,00-0037816,Romeo Doubs,WR,GB,0.410896,230.0,0.107865,0.303030
20,00-0033293,Aaron Jones,RB,MIN,0.482696,165.0,0.105338,0.377358
52,00-0036550,Rashod Bateman,WR,BAL,0.393501,245.0,0.103646,0.289855

In [187]:
simulate_betting(ev, scorers)

{'bets': 19, 'hits': 6, 'hit_rate': 0.316, 'total_profit': 38.0, 'roi': 0.2}

,player_id,player_display_name,team,position,price,predicted_touchdown_probability,model_edge,tds,hit,profit,return
0,00-0036912,DeVonta Smith,PHI,WR,180.0,0.539514,0.182371,0,False,-10.0,0.0
1,00-0036158,J.K. Dobbins,DEN,RB,160.0,0.514653,0.130037,1,True,16.0,26.0
2,00-0035676,A.J. Brown,PHI,WR,160.0,0.503039,0.118423,0,False,-10.0,0.0
3,00-0033293,Aaron Jones,MIN,RB,165.0,0.482696,0.105338,1,True,16.5,26.5
4,00-0037744,Trey McBride,ARI,TE,200.0,0.482534,0.149201,0,False,-10.0,0.0
5,00-0034960,Jakobi Meyers,LV,WR,225.0,0.466541,0.158849,0,False,-10.0,0.0
6,00-0038544,Quentin Johnston,LAC,WR,370.0,0.466127,0.253361,2,True,37.0,47.0
7,00-0034827,DJ Moore,CHI,WR,195.0,0.465005,0.126022,0,False,-10.0,0.0
8,00-0036252,Michael Pittman,IND,WR,215.0,0.446195,0.128735,1,True,21.5,31.5
9,00-0033885,David Njoku,CLE,TE,230.0,0.436788,0.133757,0,False,-10.0,0.0
10,00-0033858,Jonnu Smith,PIT,TE,400.0,0.434329,0.234329,1,True,40.0,50.0
11,00-0036139,Rico Dowdle,CAR,RB,320.0,0.430344,0.192249,0,False,-10.0,0.0
12,00-0037816,Romeo Doubs,GB,WR,230.0,0.410896,0.107865,0,False,-10.0,0.0
13,00-0036894,Pat Freiermuth,PIT,TE,425.0,0.405808,0.215332,0,False,-10.0,0.0
14,00-0038117,Wan'Dale Robinson,NYG,WR,400.0,0.403713,0.203713,0,False,-10.0,0.0
15,00-0036550,Rashod Bateman,BAL,WR,245.0,0.393501,0.103646,0,False,-10.0,0.0
16,00-0038997,Josh Downs,IND,WR,270.0,0.386269,0.115998,0,False,-10.0,0.0
17,00-0039165,Zach Charbonnet,SEA,RB,370.0,0.385771,0.173005,1,True,37.0,47.0
18,00-0037256,Rachaad White,TB,RB,320.0,0.361963,0.123868,0,False,-10.0,0.0

In [242]:
### Get top 10 rb, wr, te, qb from predictions
top_rb = predictions[predictions['position'] == 'RB'].sort_values('predicted_touchdown_probability', ascending=False).head(10)
top_wr = predictions[predictions['position'] == 'WR'].sort_values('predicted_touchdown_probability', ascending=False).head(15)
top_te = predictions[predictions['position'] == 'TE'].sort_values('predicted_touchdown_probability', ascending=False).head(5)
top_qb = predictions[predictions['position'] == 'QB'].sort_values('predicted_touchdown_probability', ascending=False).head(5)

top_rb

,player_id,player_display_name,position,team,predicted_touchdown_probability,price,model_edge,market_implied_prob
0,00-0032764,Derrick Henry,RB,BAL,0.610808,-145.0,0.018972,0.591837
1,00-0039361,Bucky Irving,RB,TB,0.597314,-140.0,0.013981,0.583333
2,00-0039040,De'Von Achane,RB,MIA,0.574486,-140.0,-0.008847,0.583333
3,00-0034844,Saquon Barkley,RB,PHI,0.573298,-185.0,-0.075825,0.649123
4,00-0035700,Josh Jacobs,RB,GB,0.570906,-160.0,-0.044478,0.615385
5,00-0033553,James Conner,RB,ARI,0.570442,-155.0,-0.037401,0.607843
6,00-0036555,Chuba Hubbard,RB,CAR,0.548293,-105.0,0.036098,0.512195
7,00-0037840,Kyren Williams,RB,LA,0.548109,-140.0,-0.035224,0.583333
8,00-0039139,Jahmyr Gibbs,RB,DET,0.547903,-105.0,0.035707,0.512195
9,00-0038597,Chase Brown,RB,CIN,0.547071,-150.0,-0.052929,0.600000

In [243]:
simulate_betting(top_rb, scorers)

{'bets': 10, 'hits': 9, 'hit_rate': 0.9, 'total_profit': 52.62, 'roi': 0.526}

,player_id,player_display_name,team,position,price,predicted_touchdown_probability,model_edge,tds,hit,profit,return
0,00-0032764,Derrick Henry,BAL,RB,-145.0,0.610808,0.018972,2,True,6.896552,16.896552
1,00-0039361,Bucky Irving,TB,RB,-140.0,0.597314,0.013981,1,True,7.142857,17.142857
2,00-0039040,De'Von Achane,MIA,RB,-140.0,0.574486,-0.008847,1,True,7.142857,17.142857
3,00-0034844,Saquon Barkley,PHI,RB,-185.0,0.573298,-0.075825,1,True,5.405405,15.405405
4,00-0035700,Josh Jacobs,GB,RB,-160.0,0.570906,-0.044478,1,True,6.250000,16.250000
5,00-0033553,James Conner,ARI,RB,-155.0,0.570442,-0.037401,1,True,6.451613,16.451613
6,00-0036555,Chuba Hubbard,CAR,RB,-105.0,0.548293,0.036098,1,True,9.523810,19.523810
7,00-0037840,Kyren Williams,LA,RB,-140.0,0.548109,-0.035224,1,True,7.142857,17.142857
8,00-0039139,Jahmyr Gibbs,DET,RB,-105.0,0.547903,0.035707,0,False,-10.000000,0.000000
9,00-0038597,Chase Brown,CIN,RB,-150.0,0.547071,-0.052929,1,True,6.666667,16.666667

In [244]:
#filter top_wr to only include players with model_edge > 0.05 and price < 500
#top_wr = top_wr[top_wr['model_edge'] > 0.05]
#top_wr = top_wr[top_wr['price'] < 500]
simulate_betting(top_wr, scorers)

{'bets': 15,
 'hits': 4,
 'hit_rate': 0.267,
 'total_profit': -25.0,
 'roi': -0.167}

,player_id,player_display_name,team,position,price,predicted_touchdown_probability,model_edge,tds,hit,profit,return
0,00-0036912,DeVonta Smith,PHI,WR,180.0,0.539514,0.182371,0,False,-10.0,0.0
1,00-0036900,Ja'Marr Chase,CIN,WR,-130.0,0.536732,-0.028486,0,False,-10.0,0.0
2,00-0039893,Brian Thomas Jr.,JAX,WR,130.0,0.518793,0.084011,1,True,13.0,23.0
3,00-0031408,Mike Evans,TB,WR,110.0,0.515207,0.039016,0,False,-10.0,0.0
4,00-0035676,A.J. Brown,PHI,WR,160.0,0.503039,0.118423,0,False,-10.0,0.0
5,00-0035659,Terry McLaurin,WAS,WR,130.0,0.503017,0.068234,0,False,-10.0,0.0
6,00-0039075,Puka Nacua,LA,WR,140.0,0.481319,0.064652,0,False,-10.0,0.0
7,00-0034348,Courtland Sutton,DEN,WR,135.0,0.478425,0.052893,1,True,13.5,23.5
8,00-0034960,Jakobi Meyers,LV,WR,225.0,0.466541,0.158849,0,False,-10.0,0.0
9,00-0038544,Quentin Johnston,LAC,WR,370.0,0.466127,0.253361,2,True,37.0,47.0
10,00-0039337,Malik Nabers,NYG,WR,150.0,0.465586,0.065586,0,False,-10.0,0.0
11,00-0034827,DJ Moore,CHI,WR,195.0,0.465005,0.126022,0,False,-10.0,0.0
12,00-0031381,Davante Adams,LA,WR,145.0,0.463883,0.055720,0,False,-10.0,0.0
13,00-0037238,Drake London,ATL,WR,125.0,0.455290,0.010846,0,False,-10.0,0.0
14,00-0036252,Michael Pittman,IND,WR,215.0,0.446195,0.128735,1,True,21.5,31.5

In [245]:
simulate_betting(top_te, scorers)

{'bets': 5, 'hits': 2, 'hit_rate': 0.4, 'total_profit': 26.5, 'roi': 0.53}

,player_id,player_display_name,team,position,price,predicted_touchdown_probability,model_edge,tds,hit,profit,return
0,00-0037744,Trey McBride,ARI,TE,200.0,0.482534,0.149201,0,False,-10.0,0.0
1,00-0030506,Travis Kelce,KC,TE,165.0,0.472411,0.095053,1,True,16.5,26.5
2,00-0033885,David Njoku,CLE,TE,230.0,0.436788,0.133757,0,False,-10.0,0.0
3,00-0033858,Jonnu Smith,PIT,TE,400.0,0.434329,0.234329,1,True,40.0,50.0
4,00-0034753,Mark Andrews,BAL,TE,205.0,0.421154,0.093285,0,False,-10.0,0.0

In [246]:
simulate_betting(top_qb, scorers)

{'bets': 5, 'hits': 4, 'hit_rate': 0.8, 'total_profit': 44.5, 'roi': 0.89}

,player_id,player_display_name,team,position,price,predicted_touchdown_probability,model_edge,tds,hit,profit,return
0,00-0034857,Josh Allen,BUF,QB,-120.0,0.471089,-0.074365,2,True,8.333333,18.333333
1,00-0036389,Jalen Hurts,PHI,QB,-150.0,0.441697,-0.158303,2,True,6.666667,16.666667
2,00-0034796,Lamar Jackson,BAL,QB,205.0,0.387036,0.059168,1,True,20.500000,30.500000
3,00-0035710,Daniel Jones,IND,QB,190.0,0.381421,0.036594,2,True,19.000000,29.000000
4,00-0039910,Jayden Daniels,WAS,QB,170.0,0.261250,-0.109120,0,False,-10.000000,0.000000

In [247]:
top_predictors = predictions[predictions['predicted_touchdown_probability'] >= 0.50]
simulate_betting(top_predictors, scorers)

{'bets': 20, 'hits': 13, 'hit_rate': 0.65, 'total_profit': 37.84, 'roi': 0.189}

,player_id,player_display_name,team,position,price,predicted_touchdown_probability,model_edge,tds,hit,profit,return
0,00-0032764,Derrick Henry,BAL,RB,-145.0,0.610808,0.018972,2,True,6.896552,16.896552
1,00-0039361,Bucky Irving,TB,RB,-140.0,0.597314,0.013981,1,True,7.142857,17.142857
2,00-0039040,De'Von Achane,MIA,RB,-140.0,0.574486,-0.008847,1,True,7.142857,17.142857
3,00-0034844,Saquon Barkley,PHI,RB,-185.0,0.573298,-0.075825,1,True,5.405405,15.405405
4,00-0035700,Josh Jacobs,GB,RB,-160.0,0.570906,-0.044478,1,True,6.250000,16.250000
5,00-0033553,James Conner,ARI,RB,-155.0,0.570442,-0.037401,1,True,6.451613,16.451613
6,00-0036555,Chuba Hubbard,CAR,RB,-105.0,0.548293,0.036098,1,True,9.523810,19.523810
7,00-0037840,Kyren Williams,LA,RB,-140.0,0.548109,-0.035224,1,True,7.142857,17.142857
8,00-0039139,Jahmyr Gibbs,DET,RB,-105.0,0.547903,0.035707,0,False,-10.000000,0.000000
9,00-0038597,Chase Brown,CIN,RB,-150.0,0.547071,-0.052929,1,True,6.666667,16.666667
10,00-0038542,Bijan Robinson,ATL,RB,-175.0,0.545828,-0.090536,1,True,5.714286,15.714286
11,00-0036223,Jonathan Taylor,IND,RB,-180.0,0.540143,-0.102714,0,False,-10.000000,0.000000
12,00-0036912,DeVonta Smith,PHI,WR,180.0,0.539514,0.182371,0,False,-10.000000,0.000000
13,00-0036900,Ja'Marr Chase,CIN,WR,-130.0,0.536732,-0.028486,0,False,-10.000000,0.000000
14,00-0037248,James Cook,BUF,RB,105.0,0.528006,0.040201,1,True,10.500000,20.500000
15,00-0039893,Brian Thomas Jr.,JAX,WR,130.0,0.518793,0.084011,1,True,13.000000,23.000000
16,00-0031408,Mike Evans,TB,WR,110.0,0.515207,0.039016,0,False,-10.000000,0.000000
17,00-0036158,J.K. Dobbins,DEN,RB,160.0,0.514653,0.130037,1,True,16.000000,26.000000
18,00-0035676,A.J. Brown,PHI,WR,160.0,0.503039,0.118423,0,False,-10.000000,0.000000
19,00-0035659,Terry McLaurin,WAS,WR,130.0,0.503017,0.068234,0,False,-10.000000,0.000000

In [248]:
vegas_similar = predictions[predictions['model_edge'] < 0.05]
vegas_similar = vegas_similar[vegas_similar['model_edge'] > 0]
vegas_similar = vegas_similar[vegas_similar['price'] < 300]
simulate_betting(vegas_similar, scorers)

{'bets': 23,
 'hits': 9,
 'hit_rate': 0.391,
 'total_profit': -2.44,
 'roi': -0.011}

,player_id,player_display_name,team,position,price,predicted_touchdown_probability,model_edge,tds,hit,profit,return
0,00-0032764,Derrick Henry,BAL,RB,-145.0,0.610808,0.018972,2,True,6.896552,16.896552
1,00-0039361,Bucky Irving,TB,RB,-140.0,0.597314,0.013981,1,True,7.142857,17.142857
2,00-0036555,Chuba Hubbard,CAR,RB,-105.0,0.548293,0.036098,1,True,9.523810,19.523810
3,00-0039139,Jahmyr Gibbs,DET,RB,-105.0,0.547903,0.035707,0,False,-10.000000,0.000000
4,00-0037248,James Cook,BUF,RB,105.0,0.528006,0.040201,1,True,10.500000,20.500000
5,00-0031408,Mike Evans,TB,WR,110.0,0.515207,0.039016,0,False,-10.000000,0.000000
6,00-0037238,Drake London,ATL,WR,125.0,0.455290,0.010846,0,False,-10.000000,0.000000
7,00-0039849,Marvin Harrison Jr.,ARI,WR,150.0,0.403806,0.003806,1,True,15.000000,25.000000
8,00-0039384,Tyrone Tracy Jr.,NYG,RB,160.0,0.400951,0.016336,0,False,-10.000000,0.000000
9,00-0036893,Najee Harris,LAC,RB,185.0,0.386058,0.035180,0,False,-10.000000,0.000000
10,00-0035710,Daniel Jones,IND,QB,190.0,0.381421,0.036594,2,True,19.000000,29.000000
11,00-0031588,Stefon Diggs,NE,WR,175.0,0.378219,0.014583,0,False,-10.000000,0.000000
12,00-0039915,Ladd McConkey,LAC,WR,180.0,0.377281,0.020138,0,False,-10.000000,0.000000
13,00-0030061,Zach Ertz,WAS,TE,200.0,0.365058,0.031725,1,True,20.000000,30.000000
14,00-0039338,Brock Bowers,LV,TE,190.0,0.356111,0.011283,0,False,-10.000000,0.000000
15,00-0038996,Tucker Kraft,GB,TE,215.0,0.350923,0.033463,1,True,21.500000,31.500000
16,00-0039065,Sam LaPorta,DET,TE,235.0,0.340404,0.041897,0,False,-10.000000,0.000000
17,00-0036613,Jaylen Waddle,MIA,WR,205.0,0.339386,0.011517,0,False,-10.000000,0.000000
18,00-0037261,Khalil Shakir,BUF,WR,225.0,0.336448,0.028756,0,False,-10.000000,0.000000
19,00-0033881,Evan Engram,DEN,TE,205.0,0.333371,0.005502,0,False,-10.000000,0.000000
20,00-0038976,Marvin Mims Jr.,DEN,WR,245.0,0.332209,0.042354,0,False,-10.000000,0.000000
21,00-0034351,Dallas Goedert,PHI,TE,280.0,0.312267,0.049109,0,False,-10.000000,0.000000
22,00-0038979,Cedric Tillman,CLE,WR,280.0,0.282102,0.018944,1,True,28.000000,38.000000

In [249]:
top_25 = predictions.head(25)
simulate_betting(top_25, scorers)

{'bets': 25, 'hits': 16, 'hit_rate': 0.64, 'total_profit': 64.34, 'roi': 0.257}

,player_id,player_display_name,team,position,price,predicted_touchdown_probability,model_edge,tds,hit,profit,return
0,00-0032764,Derrick Henry,BAL,RB,-145.0,0.610808,0.018972,2,True,6.896552,16.896552
1,00-0039361,Bucky Irving,TB,RB,-140.0,0.597314,0.013981,1,True,7.142857,17.142857
2,00-0039040,De'Von Achane,MIA,RB,-140.0,0.574486,-0.008847,1,True,7.142857,17.142857
3,00-0034844,Saquon Barkley,PHI,RB,-185.0,0.573298,-0.075825,1,True,5.405405,15.405405
4,00-0035700,Josh Jacobs,GB,RB,-160.0,0.570906,-0.044478,1,True,6.250000,16.250000
5,00-0033553,James Conner,ARI,RB,-155.0,0.570442,-0.037401,1,True,6.451613,16.451613
6,00-0036555,Chuba Hubbard,CAR,RB,-105.0,0.548293,0.036098,1,True,9.523810,19.523810
7,00-0037840,Kyren Williams,LA,RB,-140.0,0.548109,-0.035224,1,True,7.142857,17.142857
8,00-0039139,Jahmyr Gibbs,DET,RB,-105.0,0.547903,0.035707,0,False,-10.000000,0.000000
9,00-0038597,Chase Brown,CIN,RB,-150.0,0.547071,-0.052929,1,True,6.666667,16.666667
10,00-0038542,Bijan Robinson,ATL,RB,-175.0,0.545828,-0.090536,1,True,5.714286,15.714286
11,00-0036223,Jonathan Taylor,IND,RB,-180.0,0.540143,-0.102714,0,False,-10.000000,0.000000
12,00-0036912,DeVonta Smith,PHI,WR,180.0,0.539514,0.182371,0,False,-10.000000,0.000000
13,00-0036900,Ja'Marr Chase,CIN,WR,-130.0,0.536732,-0.028486,0,False,-10.000000,0.000000
14,00-0037248,James Cook,BUF,RB,105.0,0.528006,0.040201,1,True,10.500000,20.500000
15,00-0039893,Brian Thomas Jr.,JAX,WR,130.0,0.518793,0.084011,1,True,13.000000,23.000000
16,00-0031408,Mike Evans,TB,WR,110.0,0.515207,0.039016,0,False,-10.000000,0.000000
17,00-0036158,J.K. Dobbins,DEN,RB,160.0,0.514653,0.130037,1,True,16.000000,26.000000
18,00-0035676,A.J. Brown,PHI,WR,160.0,0.503039,0.118423,0,False,-10.000000,0.000000
19,00-0035659,Terry McLaurin,WAS,WR,130.0,0.503017,0.068234,0,False,-10.000000,0.000000
20,00-0033293,Aaron Jones,MIN,RB,165.0,0.482696,0.105338,1,True,16.500000,26.500000
21,00-0037744,Trey McBride,ARI,TE,200.0,0.482534,0.149201,0,False,-10.000000,0.000000
22,00-0039075,Puka Nacua,LA,WR,140.0,0.481319,0.064652,0,False,-10.000000,0.000000
23,00-0034348,Courtland Sutton,DEN,WR,135.0,0.478425,0.052893,1,True,13.500000,23.500000
24,00-0030506,Travis Kelce,KC,TE,165.0,0.472411,0.095053,1,True,16.500000,26.500000