In [250]:
%pip install -q nfl-data-py

import pandas as pd
import numpy as np
import nfl_data_py as nfl

WARNING: You are using pip version 21.2.4; however, version 25.2 is available.
You should consider upgrading via the '/Library/Developer/CommandLineTools/usr/bin/python3 -m pip install --upgrade pip' command.
Note: you may need to restart the kernel to use updated packages.

In [334]:
from datetime import datetime

# Set the season to analyze (e.g., 2024). Change if needed.
season = 2025
week = 1

# Load play-by-play data for the chosen season
def get_weekly_scorers(season, week):
    pbp = nfl.import_pbp_data(years=[season])

    # Filter for regular season, Week 1
    week_pbp = pbp[(pbp['week'] == week)]

    # Keep only touchdown plays
    week_tds = week_pbp[week_pbp['touchdown'] == 1]

    # Count TDs per scorer. Prefer id+name if both available, else fall back to name only
    use_cols = [c for c in ['td_player_id', 'td_player_name'] if c in week_tds.columns]
    if use_cols:
        scorers = (
            week_tds.dropna(subset=use_cols)
            .groupby(use_cols)
            .size()
            .reset_index(name='tds')
        )
        if 'td_player_id' in use_cols:
            scorers = scorers.rename(columns={'td_player_name': 'player', 'td_player_id': 'player_id'})
        else:
            scorers = scorers.rename(columns={'td_player_name': 'player'})
    else:
        # Fallback if td_* columns not present; derive from rusher/receiver
        rush = week_tds.dropna(subset=['rusher_player_id'])[['rusher_player_id', 'rusher_player_name']]
        rec = week_tds.dropna(subset=['receiver_player_id'])[['receiver_player_id', 'receiver_player_name']]
        rush.columns = ['player_id', 'player']
        rec.columns = ['player_id', 'player']
        both = pd.concat([rush, rec], ignore_index=True)
        scorers = both.groupby(['player_id', 'player']).size().reset_index(name='tds')

    return scorers

    # Show results
scorers = get_weekly_scorers(2025, 1)
scorers.head(50)

2025 done.
Downcasting floats.

     player_id        player  tds
0   00-0030061        Z.Ertz    1
1   00-0030279       K.Allen    1
2   00-0030506       T.Kelce    1
3   00-0030564     D.Hopkins    1
4   00-0032764       D.Henry    2
5   00-0033288      G.Kittle    1
6   00-0033293       A.Jones    1
7   00-0033553      J.Conner    1
8   00-0033858       J.Smith    1
9   00-0033873     P.Mahomes    1
10  00-0033906      A.Kamara    1
11  00-0034348      C.Sutton    1
12  00-0034796     L.Jackson    1
13  00-0034844     S.Barkley    1
14  00-0034857       J.Allen    2
15  00-0035644        N.Fant    1
16  00-0035700      J.Jacobs    1
17  00-0035710       D.Jones    2
18  00-0035719      D.Samuel    1
19  00-0036158     J.Dobbins    1
20  00-0036252     M.Pittman    1
21  00-0036322   J.Jefferson    1
22  00-0036389       J.Hurts    2
23  00-0036555     C.Hubbard    1
24  00-0036862   B.Skowronek    1
25  00-0036945      J.Fields    2
26  00-0036986      N.Wright    1
27  00-0036997    J.Williams    2
28  00-0037004        H.Long    1
29  00-0037112      J.Tonges    1
30  00-0037228      J.Warren    1
31  00-0037248        J.Cook    1
32  00-0037740      G.Wilson    1
33  00-0037837      C.Austin    1
34  00-0037840    K.Williams    1
35  00-0038542    B.Robinson    1
36  00-0038544    Q.Johnston    2
37  00-0038563      T.Tucker    1
38  00-0038597       C.Brown    1
39  00-0038621     D.Douglas    1
40  00-0038933     D.Kincaid    1
41  00-0038979     C.Tillman    1
42  00-0038996       T.Kraft    1
43  00-0039040      D.Achane    1
44  00-0039064     Z.Flowers    1
45  00-0039074       D.Allen    1
46  00-0039146        J.Reed    1
47  00-0039165  Z.Charbonnet    1
48  00-0039361      B.Irving    1
49  00-0039794       B.Allen    1

In [335]:
predictions = pd.read_csv(f'data/predictions_week_{week}.csv')

#Keep only player_id, player_display_name, predicted_touchdown_probability, and model_edge
predictions = predictions[['player_id', 'player_display_name', 'position','team', 'predicted_touchdown_probability', 'price', 'model_edge','market_implied_prob']]

#Sort by predicted_touchdown_probability in descending order
predictions = predictions.sort_values(by='predicted_touchdown_probability', ascending=False)

#Show the top 50 players
predictions.head(50)

,player_id,player_display_name,position,team,predicted_touchdown_probability,price,model_edge,market_implied_prob
0,00-0032764,Derrick Henry,RB,BAL,0.609973,-145.0,0.018136,0.591837
1,00-0039361,Bucky Irving,RB,TB,0.600935,-140.0,0.017602,0.583333
2,00-0038542,Bijan Robinson,RB,ATL,0.589403,-175.0,-0.046961,0.636364
3,00-0036555,Chuba Hubbard,RB,CAR,0.582197,-105.0,0.070001,0.512195
4,00-0034844,Saquon Barkley,RB,PHI,0.577634,-185.0,-0.071488,0.649123
5,00-0039040,De'Von Achane,RB,MIA,0.574298,-140.0,-0.009035,0.583333
6,00-0036223,Jonathan Taylor,RB,IND,0.552116,-180.0,-0.090742,0.642857
7,00-0039139,Jahmyr Gibbs,RB,DET,0.552014,-105.0,0.039819,0.512195
8,00-0037840,Kyren Williams,RB,LA,0.549713,-140.0,-0.033620,0.583333
9,00-0033553,James Conner,RB,ARI,0.547825,-155.0,-0.060018,0.607843
10,00-0035700,Josh Jacobs,RB,GB,0.547748,-160.0,-0.067637,0.615385
11,00-0038597,Chase Brown,RB,CIN,0.544633,-150.0,-0.055367,0.600000
12,00-0036912,DeVonta Smith,WR,PHI,0.534621,180.0,0.177478,0.357143
13,00-0036900,Ja'Marr Chase,WR,CIN,0.533280,-130.0,-0.031938,0.565217
14,00-0037248,James Cook,RB,BUF,0.527458,105.0,0.039653,0.487805
15,00-0031408,Mike Evans,WR,TB,0.515976,110.0,0.039785,0.476190
16,00-0039893,Brian Thomas Jr.,WR,JAX,0.514917,130.0,0.080135,0.434783
17,00-0036158,J.K. Dobbins,RB,DEN,0.511576,160.0,0.126961,0.384615
18,00-0033293,Aaron Jones,RB,MIN,0.505491,165.0,0.128132,0.377358
19,00-0035676,A.J. Brown,WR,PHI,0.496160,160.0,0.111544,0.384615
20,00-0037744,Trey McBride,TE,ARI,0.495164,200.0,0.161831,0.333333
21,00-0039075,Puka Nacua,WR,LA,0.489732,140.0,0.073066,0.416667
22,00-0035659,Terry McLaurin,WR,WAS,0.485333,130.0,0.050550,0.434783
23,00-0039337,Malik Nabers,WR,NYG,0.484836,150.0,0.084836,0.400000
24,00-0030506,Travis Kelce,TE,KC,0.481134,165.0,0.103775,0.377358
25,00-0034348,Courtland Sutton,WR,DEN,0.476793,135.0,0.051261,0.425532
26,00-0034857,Josh Allen,QB,BUF,0.473835,-120.0,-0.071619,0.545455
27,00-0034960,Jakobi Meyers,WR,LV,0.471294,225.0,0.163602,0.307692
28,00-0038544,Quentin Johnston,WR,LAC,0.468613,370.0,0.255847,0.212766
29,00-0034827,DJ Moore,WR,CHI,0.463670,195.0,0.124687,0.338983
30,00-0037238,Drake London,WR,ATL,0.460896,125.0,0.016452,0.444444
31,00-0036389,Jalen Hurts,QB,PHI,0.458598,-150.0,-0.141402,0.600000
32,00-0031381,Davante Adams,WR,LA,0.458319,145.0,0.050155,0.408163
33,00-0039894,Xavier Worthy,WR,KC,0.442016,125.0,-0.002429,0.444444
34,00-0036252,Michael Pittman,WR,IND,0.440139,215.0,0.122678,0.317460
35,00-0038120,Breece Hall,RB,NYJ,0.439557,170.0,0.069187,0.370370
36,00-0036894,Pat Freiermuth,TE,PIT,0.438417,425.0,0.247941,0.190476
37,00-0033280,Christian McCaffrey,RB,SF,0.434899,-155.0,-0.172944,0.607843
38,00-0033858,Jonnu Smith,TE,PIT,0.434041,400.0,0.234041,0.200000
39,00-0037816,Romeo Doubs,WR,GB,0.426501,230.0,0.123470,0.303030
40,00-0034753,Mark Andrews,TE,BAL,0.420391,205.0,0.092522,0.327869
41,00-0033885,David Njoku,TE,CLE,0.419178,230.0,0.116148,0.303030
42,00-0034796,Lamar Jackson,QB,BAL,0.416295,205.0,0.088426,0.327869
43,00-0039901,Keon Coleman,WR,BUF,0.410830,210.0,0.088250,0.322581
44,00-0036407,Jerry Jeudy,WR,CLE,0.410567,200.0,0.077233,0.333333
45,00-0036875,Rhamondre Stevenson,RB,NE,0.405771,155.0,0.013614,0.392157
46,00-0039384,Tyrone Tracy Jr.,RB,NYG,0.401989,160.0,0.017374,0.384615
47,00-0033906,Alvin Kamara,RB,NO,0.401604,-105.0,-0.110592,0.512195
48,00-0039849,Marvin Harrison Jr.,WR,ARI,0.401601,150.0,0.001601,0.400000
49,00-0036139,Rico Dowdle,RB,CAR,0.399474,320.0,0.161379,0.238095

In [336]:
# Join predictions with scorers: prefer player_id, else fall back to name
if 'player_id' in scorers.columns:
    pred_scored = predictions.merge(
        scorers[['player_id', 'tds']], on='player_id', how='inner'
    )
else:
    pred_scored = predictions.merge(
        scorers[['player', 'tds']], left_on='player_display_name', right_on='player', how='inner'
    )

pred_scored.sort_values(['predicted_touchdown_probability'], ascending=[False])

,player_id,player_display_name,position,team,predicted_touchdown_probability,price,model_edge,market_implied_prob,tds
0,00-0032764,Derrick Henry,RB,BAL,0.609973,-145.0,0.018136,0.591837,2
1,00-0039361,Bucky Irving,RB,TB,0.600935,-140.0,0.017602,0.583333,1
2,00-0038542,Bijan Robinson,RB,ATL,0.589403,-175.0,-0.046961,0.636364,1
3,00-0036555,Chuba Hubbard,RB,CAR,0.582197,-105.0,0.070001,0.512195,1
4,00-0034844,Saquon Barkley,RB,PHI,0.577634,-185.0,-0.071488,0.649123,1
5,00-0039040,De'Von Achane,RB,MIA,0.574298,-140.0,-0.009035,0.583333,1
6,00-0037840,Kyren Williams,RB,LA,0.549713,-140.0,-0.033620,0.583333,1
7,00-0033553,James Conner,RB,ARI,0.547825,-155.0,-0.060018,0.607843,1
8,00-0035700,Josh Jacobs,RB,GB,0.547748,-160.0,-0.067637,0.615385,1
9,00-0038597,Chase Brown,RB,CIN,0.544633,-150.0,-0.055367,0.600000,1
10,00-0037248,James Cook,RB,BUF,0.527458,105.0,0.039653,0.487805,1
11,00-0039893,Brian Thomas Jr.,WR,JAX,0.514917,130.0,0.080135,0.434783,1
12,00-0036158,J.K. Dobbins,RB,DEN,0.511576,160.0,0.126961,0.384615,1
13,00-0033293,Aaron Jones,RB,MIN,0.505491,165.0,0.128132,0.377358,1
14,00-0030506,Travis Kelce,TE,KC,0.481134,165.0,0.103775,0.377358,1
15,00-0034348,Courtland Sutton,WR,DEN,0.476793,135.0,0.051261,0.425532,1
16,00-0034857,Josh Allen,QB,BUF,0.473835,-120.0,-0.071619,0.545455,2
17,00-0038544,Quentin Johnston,WR,LAC,0.468613,370.0,0.255847,0.212766,2
18,00-0036389,Jalen Hurts,QB,PHI,0.458598,-150.0,-0.141402,0.600000,2
19,00-0036252,Michael Pittman,WR,IND,0.440139,215.0,0.122678,0.317460,1
20,00-0033858,Jonnu Smith,TE,PIT,0.434041,400.0,0.234041,0.200000,1
21,00-0034796,Lamar Jackson,QB,BAL,0.416295,205.0,0.088426,0.327869,1
22,00-0039901,Keon Coleman,WR,BUF,0.410830,210.0,0.088250,0.322581,1
23,00-0033906,Alvin Kamara,RB,NO,0.401604,-105.0,-0.110592,0.512195,1
24,00-0039849,Marvin Harrison Jr.,WR,ARI,0.401601,150.0,0.001601,0.400000,1
25,00-0039165,Zach Charbonnet,RB,SEA,0.394862,370.0,0.182096,0.212766,1
26,00-0036322,Justin Jefferson,WR,MIN,0.392437,135.0,-0.033095,0.425532,1
27,00-0030061,Zach Ertz,TE,WAS,0.371277,200.0,0.037944,0.333333,1
28,00-0035644,Noah Fant,TE,CIN,0.354579,700.0,0.229579,0.125000,1
29,00-0038996,Tucker Kraft,TE,GB,0.353071,215.0,0.035611,0.317460,1
30,00-0035710,Daniel Jones,QB,IND,0.338868,190.0,-0.005960,0.344828,2
31,00-0037228,Jaylen Warren,RB,PIT,0.312202,165.0,-0.065156,0.377358,1
32,00-0038621,DeMario Douglas,WR,NE,0.276030,340.0,0.048757,0.227273,1
33,00-0038979,Cedric Tillman,WR,CLE,0.275942,280.0,0.012784,0.263158,1
34,00-0037740,Garrett Wilson,WR,NYJ,0.262945,220.0,-0.049555,0.312500,1
35,00-0030279,Keenan Allen,WR,LAC,0.226592,275.0,-0.040075,0.266667,1
36,00-0038563,Tre Tucker,WR,LV,0.216000,450.0,0.034182,0.181818,1
37,00-0040122,Ashton Jeanty,RB,LV,0.213959,-120.0,-0.331496,0.545455,1
38,00-0036997,Javonte Williams,RB,DAL,0.212448,225.0,-0.095244,0.307692,2
39,00-0030564,DeAndre Hopkins,WR,BAL,0.204241,425.0,0.013765,0.190476,1
40,00-0033873,Patrick Mahomes,QB,KC,0.201707,550.0,0.047861,0.153846,1
41,00-0036945,Justin Fields,QB,NYJ,0.185523,200.0,-0.147811,0.333333,2
42,00-0039146,Jayden Reed,WR,GB,0.182931,230.0,-0.120100,0.303030,1
43,00-0039919,Rome Odunze,WR,CHI,0.180717,215.0,-0.136743,0.317460,1
44,00-0039918,Caleb Williams,QB,CHI,0.171421,650.0,0.038088,0.133333,1
45,00-0039794,Braelon Allen,RB,NYJ,0.161480,250.0,-0.124234,0.285714,1
46,00-0039917,Michael Penix Jr.,QB,ATL,0.161117,800.0,0.050006,0.111111,1
47,00-0038933,Dalton Kincaid,TE,BUF,0.142344,350.0,-0.079878,0.222222,1
48,00-0039923,J.J. McCarthy,QB,MIN,0.141770,600.0,-0.001087,0.142857,1
49,00-0033288,George Kittle,TE,SF,0.139284,150.0,-0.260716,0.400000,1
50,00-0040242,Jacory Croskey-Merritt,RB,WAS,0.127281,330.0,-0.105277,0.232558,1
51,00-0039064,Zay Flowers,WR,BAL,0.123120,200.0,-0.210213,0.333333,1
52,00-0037004,Hunter Long,TE,JAX,0.114000,1200.0,0.037077,0.076923,1
53,00-0036862,Ben Skowronek,WR,PIT,0.113029,1300.0,0.041601,0.071429,1
54,00-0035719,Deebo Samuel Sr.,WR,WAS,0.091441,195.0,-0.247542,0.338983,1
55,00-0037112,Jake Tonges,TE,SF,0.090284,1700.0,0.034729,0.055556,1
56,00-0039074,Davis Allen,TE,LA,0.085826,1700.0,0.030270,0.055556,1
57,00-0037837,Calvin Austin III,WR,PIT,0.084176,400.0,-0.115824,0.200000,1
58,00-0040129,Emeka Egbuka,WR,TB,0.059608,185.0,-0.291270,0.350877,2
59,00-0040669,Isaac TeSlaa,WR,DET,0.057900,450.0,-0.123918,0.181818,1

In [337]:
###Simulate betting on the top 10 running backs
def simulate_betting(df, scorers):
    stake = 10.0

    bets = df.copy()

    # Merge to mark hits
    bets = bets.merge(
        scorers[['player_id', 'tds']], on='player_id', how='left'
    )
    bets['tds'] = bets['tds'].fillna(0).astype(int)
    bets['hit'] = bets['tds'] > 0

    # American odds payout logic
    # profit_if_win = stake * (odds/100) if odds > 0 else stake * (100/abs(odds))
    # profit_if_loss = -stake
    is_plus = bets['price'] > 0
    profit_if_win = stake * (bets['price'] / 100.0)
    profit_if_win = profit_if_win.where(is_plus, stake * (100.0 / bets['price'].abs()))

    bets['profit'] = np.where(bets['hit'], profit_if_win, -stake)

    # Add total return
    bets['return'] = stake + bets['profit']

    # Summary metrics
    num_bets = len(bets)
    hits = int(bets['hit'].sum())
    hit_rate = hits / num_bets if num_bets else 0.0
    total_profit = float(bets['profit'].sum())
    roi = total_profit / (stake * num_bets) if num_bets else 0.0

    summary = {
        'bets': num_bets,
        'hits': hits,
        'hit_rate': round(hit_rate, 3),
        'total_profit': round(total_profit, 2),
        'roi': round(roi, 3)
    }

    display(summary)

    # Show detailed results
    cols = [
        'player_id', 'player_display_name', 'team', 'position', 'price',
        'predicted_touchdown_probability', 'model_edge', 'tds', 'hit', 'profit', 'return'
    ]
    return bets[cols].sort_values(['predicted_touchdown_probability'], ascending=[False]).reset_index(drop=True)

In [338]:
# output players from predictions that play for 'PHI', 'KC', 'LAC' or 'DAL'

#find players with model_edge > 0 and price < 500
ev = predictions[predictions['model_edge'] > 0.10] 
ev = ev[ev['price'] <= 400]

#sort by model_edge in descending order
ev = ev.sort_values('model_edge', ascending=False)
ev

,player_id,player_display_name,position,team,predicted_touchdown_probability,price,model_edge,market_implied_prob
28,00-0038544,Quentin Johnston,WR,LAC,0.468613,370.0,0.255847,0.212766
38,00-0033858,Jonnu Smith,TE,PIT,0.434041,400.0,0.234041,0.200000
55,00-0038117,Wan'Dale Robinson,WR,NYG,0.391703,400.0,0.191703,0.200000
51,00-0039165,Zach Charbonnet,RB,SEA,0.394862,370.0,0.182096,0.212766
12,00-0036912,DeVonta Smith,WR,PHI,0.534621,180.0,0.177478,0.357143
27,00-0034960,Jakobi Meyers,WR,LV,0.471294,225.0,0.163602,0.307692
20,00-0037744,Trey McBride,TE,ARI,0.495164,200.0,0.161831,0.333333
49,00-0036139,Rico Dowdle,RB,CAR,0.399474,320.0,0.161379,0.238095
18,00-0033293,Aaron Jones,RB,MIN,0.505491,165.0,0.128132,0.377358
17,00-0036158,J.K. Dobbins,RB,DEN,0.511576,160.0,0.126961,0.384615
50,00-0038997,Josh Downs,WR,IND,0.394996,270.0,0.124725,0.270270
29,00-0034827,DJ Moore,WR,CHI,0.463670,195.0,0.124687,0.338983
65,00-0037256,Rachaad White,RB,TB,0.362060,320.0,0.123965,0.238095
39,00-0037816,Romeo Doubs,WR,GB,0.426501,230.0,0.123470,0.303030
34,00-0036252,Michael Pittman,WR,IND,0.440139,215.0,0.122678,0.317460
41,00-0033885,David Njoku,TE,CLE,0.419178,230.0,0.116148,0.303030
19,00-0035676,A.J. Brown,WR,PHI,0.496160,160.0,0.111544,0.384615
24,00-0030506,Travis Kelce,TE,KC,0.481134,165.0,0.103775,0.377358

In [339]:
simulate_betting(ev, scorers)

{'bets': 18, 'hits': 7, 'hit_rate': 0.389, 'total_profit': 74.5, 'roi': 0.414}

,player_id,player_display_name,team,position,price,predicted_touchdown_probability,model_edge,tds,hit,profit,return
0,00-0036912,DeVonta Smith,PHI,WR,180.0,0.534621,0.177478,0,False,-10.0,0.0
1,00-0036158,J.K. Dobbins,DEN,RB,160.0,0.511576,0.126961,1,True,16.0,26.0
2,00-0033293,Aaron Jones,MIN,RB,165.0,0.505491,0.128132,1,True,16.5,26.5
3,00-0035676,A.J. Brown,PHI,WR,160.0,0.496160,0.111544,0,False,-10.0,0.0
4,00-0037744,Trey McBride,ARI,TE,200.0,0.495164,0.161831,0,False,-10.0,0.0
5,00-0030506,Travis Kelce,KC,TE,165.0,0.481134,0.103775,1,True,16.5,26.5
6,00-0034960,Jakobi Meyers,LV,WR,225.0,0.471294,0.163602,0,False,-10.0,0.0
7,00-0038544,Quentin Johnston,LAC,WR,370.0,0.468613,0.255847,2,True,37.0,47.0
8,00-0034827,DJ Moore,CHI,WR,195.0,0.463670,0.124687,0,False,-10.0,0.0
9,00-0036252,Michael Pittman,IND,WR,215.0,0.440139,0.122678,1,True,21.5,31.5
10,00-0033858,Jonnu Smith,PIT,TE,400.0,0.434041,0.234041,1,True,40.0,50.0
11,00-0037816,Romeo Doubs,GB,WR,230.0,0.426501,0.123470,0,False,-10.0,0.0
12,00-0033885,David Njoku,CLE,TE,230.0,0.419178,0.116148,0,False,-10.0,0.0
13,00-0036139,Rico Dowdle,CAR,RB,320.0,0.399474,0.161379,0,False,-10.0,0.0
14,00-0038997,Josh Downs,IND,WR,270.0,0.394996,0.124725,0,False,-10.0,0.0
15,00-0039165,Zach Charbonnet,SEA,RB,370.0,0.394862,0.182096,1,True,37.0,47.0
16,00-0038117,Wan'Dale Robinson,NYG,WR,400.0,0.391703,0.191703,0,False,-10.0,0.0
17,00-0037256,Rachaad White,TB,RB,320.0,0.362060,0.123965,0,False,-10.0,0.0

In [ ]:
### Get top 10 rb, wr, te, qb from predictions
top_rb = predictions[predictions['position'] == 'RB'].sort_values('predicted_touchdown_probability', ascending=False).head(10)
top_wr = predictions[predictions['position'] == 'WR'].sort_values('predicted_touchdown_probability', ascending=False).head(15)
top_te = predictions[predictions['position'] == 'TE'].sort_values('predicted_touchdown_probability', ascending=False).head(5)
top_qb = predictions[predictions['position'] == 'QB'].sort_values('predicted_touchdown_probability', ascending=False).head(5)

top_rb

,player_id,player_display_name,position,team,predicted_touchdown_probability,price,model_edge,market_implied_prob
0,00-0032764,Derrick Henry,RB,BAL,0.609973,-145.0,0.018136,0.591837
1,00-0039361,Bucky Irving,RB,TB,0.600935,-140.0,0.017602,0.583333
2,00-0038542,Bijan Robinson,RB,ATL,0.589403,-175.0,-0.046961,0.636364
3,00-0036555,Chuba Hubbard,RB,CAR,0.582197,-105.0,0.070001,0.512195
4,00-0034844,Saquon Barkley,RB,PHI,0.577634,-185.0,-0.071488,0.649123
5,00-0039040,De'Von Achane,RB,MIA,0.574298,-140.0,-0.009035,0.583333
6,00-0036223,Jonathan Taylor,RB,IND,0.552116,-180.0,-0.090742,0.642857
7,00-0039139,Jahmyr Gibbs,RB,DET,0.552014,-105.0,0.039819,0.512195
8,00-0037840,Kyren Williams,RB,LA,0.549713,-140.0,-0.033620,0.583333
9,00-0033553,James Conner,RB,ARI,0.547825,-155.0,-0.060018,0.607843

In [341]:
simulate_betting(top_rb, scorers)

{'bets': 10, 'hits': 8, 'hit_rate': 0.8, 'total_profit': 35.42, 'roi': 0.354}

,player_id,player_display_name,team,position,price,predicted_touchdown_probability,model_edge,tds,hit,profit,return
0,00-0032764,Derrick Henry,BAL,RB,-145.0,0.609973,0.018136,2,True,6.896552,16.896552
1,00-0039361,Bucky Irving,TB,RB,-140.0,0.600935,0.017602,1,True,7.142857,17.142857
2,00-0038542,Bijan Robinson,ATL,RB,-175.0,0.589403,-0.046961,1,True,5.714286,15.714286
3,00-0036555,Chuba Hubbard,CAR,RB,-105.0,0.582197,0.070001,1,True,9.523810,19.523810
4,00-0034844,Saquon Barkley,PHI,RB,-185.0,0.577634,-0.071488,1,True,5.405405,15.405405
5,00-0039040,De'Von Achane,MIA,RB,-140.0,0.574298,-0.009035,1,True,7.142857,17.142857
6,00-0036223,Jonathan Taylor,IND,RB,-180.0,0.552116,-0.090742,0,False,-10.000000,0.000000
7,00-0039139,Jahmyr Gibbs,DET,RB,-105.0,0.552014,0.039819,0,False,-10.000000,0.000000
8,00-0037840,Kyren Williams,LA,RB,-140.0,0.549713,-0.033620,1,True,7.142857,17.142857
9,00-0033553,James Conner,ARI,RB,-155.0,0.547825,-0.060018,1,True,6.451613,16.451613

In [342]:
#filter top_wr to only include players with model_edge > 0.05 and price < 500
#top_wr = top_wr[top_wr['model_edge'] > 0.05]
#top_wr = top_wr[top_wr['price'] < 500]
simulate_betting(top_wr, scorers)

{'bets': 15, 'hits': 3, 'hit_rate': 0.2, 'total_profit': -56.5, 'roi': -0.377}

,player_id,player_display_name,team,position,price,predicted_touchdown_probability,model_edge,tds,hit,profit,return
0,00-0036912,DeVonta Smith,PHI,WR,180.0,0.534621,0.177478,0,False,-10.0,0.0
1,00-0036900,Ja'Marr Chase,CIN,WR,-130.0,0.533280,-0.031938,0,False,-10.0,0.0
2,00-0031408,Mike Evans,TB,WR,110.0,0.515976,0.039785,0,False,-10.0,0.0
3,00-0039893,Brian Thomas Jr.,JAX,WR,130.0,0.514917,0.080135,1,True,13.0,23.0
4,00-0035676,A.J. Brown,PHI,WR,160.0,0.496160,0.111544,0,False,-10.0,0.0
5,00-0039075,Puka Nacua,LA,WR,140.0,0.489732,0.073066,0,False,-10.0,0.0
6,00-0035659,Terry McLaurin,WAS,WR,130.0,0.485333,0.050550,0,False,-10.0,0.0
7,00-0039337,Malik Nabers,NYG,WR,150.0,0.484836,0.084836,0,False,-10.0,0.0
8,00-0034348,Courtland Sutton,DEN,WR,135.0,0.476793,0.051261,1,True,13.5,23.5
9,00-0034960,Jakobi Meyers,LV,WR,225.0,0.471294,0.163602,0,False,-10.0,0.0
10,00-0038544,Quentin Johnston,LAC,WR,370.0,0.468613,0.255847,2,True,37.0,47.0
11,00-0034827,DJ Moore,CHI,WR,195.0,0.463670,0.124687,0,False,-10.0,0.0
12,00-0037238,Drake London,ATL,WR,125.0,0.460896,0.016452,0,False,-10.0,0.0
13,00-0031381,Davante Adams,LA,WR,145.0,0.458319,0.050155,0,False,-10.0,0.0
14,00-0039894,Xavier Worthy,KC,WR,125.0,0.442016,-0.002429,0,False,-10.0,0.0

In [343]:
simulate_betting(top_te, scorers)

{'bets': 5, 'hits': 2, 'hit_rate': 0.4, 'total_profit': 26.5, 'roi': 0.53}

,player_id,player_display_name,team,position,price,predicted_touchdown_probability,model_edge,tds,hit,profit,return
0,00-0037744,Trey McBride,ARI,TE,200.0,0.495164,0.161831,0,False,-10.0,0.0
1,00-0030506,Travis Kelce,KC,TE,165.0,0.481134,0.103775,1,True,16.5,26.5
2,00-0036894,Pat Freiermuth,PIT,TE,425.0,0.438417,0.247941,0,False,-10.0,0.0
3,00-0033858,Jonnu Smith,PIT,TE,400.0,0.434041,0.234041,1,True,40.0,50.0
4,00-0034753,Mark Andrews,BAL,TE,205.0,0.420391,0.092522,0,False,-10.0,0.0

In [344]:
simulate_betting(top_qb, scorers)

{'bets': 5, 'hits': 4, 'hit_rate': 0.8, 'total_profit': 44.5, 'roi': 0.89}

,player_id,player_display_name,team,position,price,predicted_touchdown_probability,model_edge,tds,hit,profit,return
0,00-0034857,Josh Allen,BUF,QB,-120.0,0.473835,-0.071619,2,True,8.333333,18.333333
1,00-0036389,Jalen Hurts,PHI,QB,-150.0,0.458598,-0.141402,2,True,6.666667,16.666667
2,00-0034796,Lamar Jackson,BAL,QB,205.0,0.416295,0.088426,1,True,20.500000,30.500000
3,00-0035710,Daniel Jones,IND,QB,190.0,0.338868,-0.005960,2,True,19.000000,29.000000
4,00-0039910,Jayden Daniels,WAS,QB,170.0,0.261527,-0.108844,0,False,-10.000000,0.000000

In [365]:
top_predictors = predictions[predictions['predicted_touchdown_probability'] >= 0.50]
simulate_betting(top_predictors, scorers)

{'bets': 19,
 'hits': 14,
 'hit_rate': 0.737,
 'total_profit': 74.34,
 'roi': 0.391}

,player_id,player_display_name,team,position,price,predicted_touchdown_probability,model_edge,tds,hit,profit,return
0,00-0032764,Derrick Henry,BAL,RB,-145.0,0.609973,0.018136,2,True,6.896552,16.896552
1,00-0039361,Bucky Irving,TB,RB,-140.0,0.600935,0.017602,1,True,7.142857,17.142857
2,00-0038542,Bijan Robinson,ATL,RB,-175.0,0.589403,-0.046961,1,True,5.714286,15.714286
3,00-0036555,Chuba Hubbard,CAR,RB,-105.0,0.582197,0.070001,1,True,9.523810,19.523810
4,00-0034844,Saquon Barkley,PHI,RB,-185.0,0.577634,-0.071488,1,True,5.405405,15.405405
5,00-0039040,De'Von Achane,MIA,RB,-140.0,0.574298,-0.009035,1,True,7.142857,17.142857
6,00-0036223,Jonathan Taylor,IND,RB,-180.0,0.552116,-0.090742,0,False,-10.000000,0.000000
7,00-0039139,Jahmyr Gibbs,DET,RB,-105.0,0.552014,0.039819,0,False,-10.000000,0.000000
8,00-0037840,Kyren Williams,LA,RB,-140.0,0.549713,-0.033620,1,True,7.142857,17.142857
9,00-0033553,James Conner,ARI,RB,-155.0,0.547825,-0.060018,1,True,6.451613,16.451613
10,00-0035700,Josh Jacobs,GB,RB,-160.0,0.547748,-0.067637,1,True,6.250000,16.250000
11,00-0038597,Chase Brown,CIN,RB,-150.0,0.544633,-0.055367,1,True,6.666667,16.666667
12,00-0036912,DeVonta Smith,PHI,WR,180.0,0.534621,0.177478,0,False,-10.000000,0.000000
13,00-0036900,Ja'Marr Chase,CIN,WR,-130.0,0.533280,-0.031938,0,False,-10.000000,0.000000
14,00-0037248,James Cook,BUF,RB,105.0,0.527458,0.039653,1,True,10.500000,20.500000
15,00-0031408,Mike Evans,TB,WR,110.0,0.515976,0.039785,0,False,-10.000000,0.000000
16,00-0039893,Brian Thomas Jr.,JAX,WR,130.0,0.514917,0.080135,1,True,13.000000,23.000000
17,00-0036158,J.K. Dobbins,DEN,RB,160.0,0.511576,0.126961,1,True,16.000000,26.000000
18,00-0033293,Aaron Jones,MIN,RB,165.0,0.505491,0.128132,1,True,16.500000,26.500000

In [389]:
top_vegas = predictions.sort_values('market_implied_prob', ascending=False).head(19)
simulate_betting(top_vegas, scorers)

{'bets': 19,
 'hits': 15,
 'hit_rate': 0.789,
 'total_profit': 71.69,
 'roi': 0.377}

,player_id,player_display_name,team,position,price,predicted_touchdown_probability,model_edge,tds,hit,profit,return
0,00-0032764,Derrick Henry,BAL,RB,-145.0,0.609973,0.018136,2,True,6.896552,16.896552
1,00-0039361,Bucky Irving,TB,RB,-140.0,0.600935,0.017602,1,True,7.142857,17.142857
2,00-0038542,Bijan Robinson,ATL,RB,-175.0,0.589403,-0.046961,1,True,5.714286,15.714286
3,00-0036555,Chuba Hubbard,CAR,RB,-105.0,0.582197,0.070001,1,True,9.523810,19.523810
4,00-0034844,Saquon Barkley,PHI,RB,-185.0,0.577634,-0.071488,1,True,5.405405,15.405405
5,00-0039040,De'Von Achane,MIA,RB,-140.0,0.574298,-0.009035,1,True,7.142857,17.142857
6,00-0036223,Jonathan Taylor,IND,RB,-180.0,0.552116,-0.090742,0,False,-10.000000,0.000000
7,00-0039139,Jahmyr Gibbs,DET,RB,-105.0,0.552014,0.039819,0,False,-10.000000,0.000000
8,00-0037840,Kyren Williams,LA,RB,-140.0,0.549713,-0.033620,1,True,7.142857,17.142857
9,00-0033553,James Conner,ARI,RB,-155.0,0.547825,-0.060018,1,True,6.451613,16.451613
10,00-0035700,Josh Jacobs,GB,RB,-160.0,0.547748,-0.067637,1,True,6.250000,16.250000
11,00-0038597,Chase Brown,CIN,RB,-150.0,0.544633,-0.055367,1,True,6.666667,16.666667
12,00-0036900,Ja'Marr Chase,CIN,WR,-130.0,0.533280,-0.031938,0,False,-10.000000,0.000000
13,00-0037248,James Cook,BUF,RB,105.0,0.527458,0.039653,1,True,10.500000,20.500000
14,00-0034857,Josh Allen,BUF,QB,-120.0,0.473835,-0.071619,2,True,8.333333,18.333333
15,00-0036389,Jalen Hurts,PHI,QB,-150.0,0.458598,-0.141402,2,True,6.666667,16.666667
16,00-0033280,Christian McCaffrey,SF,RB,-155.0,0.434899,-0.172944,0,False,-10.000000,0.000000
17,00-0033906,Alvin Kamara,NO,RB,-105.0,0.401604,-0.110592,1,True,9.523810,19.523810
18,00-0040122,Ashton Jeanty,LV,RB,-120.0,0.213959,-0.331496,1,True,8.333333,18.333333

In [390]:
vegas_similar = predictions[predictions['model_edge'] < 0.05]
vegas_similar = vegas_similar[vegas_similar['model_edge'] > 0]
vegas_similar = vegas_similar[vegas_similar['price'] < 300]
simulate_betting(vegas_similar, scorers)

{'bets': 22,
 'hits': 7,
 'hit_rate': 0.318,
 'total_profit': -40.96,
 'roi': -0.186}

,player_id,player_display_name,team,position,price,predicted_touchdown_probability,model_edge,tds,hit,profit,return
0,00-0032764,Derrick Henry,BAL,RB,-145.0,0.609973,0.018136,2,True,6.896552,16.896552
1,00-0039361,Bucky Irving,TB,RB,-140.0,0.600935,0.017602,1,True,7.142857,17.142857
2,00-0039139,Jahmyr Gibbs,DET,RB,-105.0,0.552014,0.039819,0,False,-10.000000,0.000000
3,00-0037248,James Cook,BUF,RB,105.0,0.527458,0.039653,1,True,10.500000,20.500000
4,00-0031408,Mike Evans,TB,WR,110.0,0.515976,0.039785,0,False,-10.000000,0.000000
5,00-0037238,Drake London,ATL,WR,125.0,0.460896,0.016452,0,False,-10.000000,0.000000
6,00-0036875,Rhamondre Stevenson,NE,RB,155.0,0.405771,0.013614,0,False,-10.000000,0.000000
7,00-0039384,Tyrone Tracy Jr.,NYG,RB,160.0,0.401989,0.017374,0,False,-10.000000,0.000000
8,00-0039849,Marvin Harrison Jr.,ARI,WR,150.0,0.401601,0.001601,1,True,15.000000,25.000000
9,00-0038555,Tank Bigsby,JAX,RB,155.0,0.392342,0.000186,0,False,-10.000000,0.000000
10,00-0036893,Najee Harris,LAC,RB,185.0,0.378851,0.027974,0,False,-10.000000,0.000000
11,00-0031588,Stefon Diggs,NE,WR,175.0,0.377759,0.014122,0,False,-10.000000,0.000000
12,00-0036275,D'Andre Swift,CHI,RB,170.0,0.374403,0.004032,0,False,-10.000000,0.000000
13,00-0030061,Zach Ertz,WAS,TE,200.0,0.371277,0.037944,1,True,20.000000,30.000000
14,00-0039915,Ladd McConkey,LAC,WR,180.0,0.370621,0.013478,0,False,-10.000000,0.000000
15,00-0038996,Tucker Kraft,GB,TE,215.0,0.353071,0.035611,1,True,21.500000,31.500000
16,00-0033881,Evan Engram,DEN,TE,205.0,0.347675,0.019806,0,False,-10.000000,0.000000
17,00-0036550,Rashod Bateman,BAL,WR,245.0,0.338185,0.048330,0,False,-10.000000,0.000000
18,00-0038976,Marvin Mims Jr.,DEN,WR,245.0,0.323663,0.033808,0,False,-10.000000,0.000000
19,00-0037261,Khalil Shakir,BUF,WR,225.0,0.319848,0.012155,0,False,-10.000000,0.000000
20,00-0034351,Dallas Goedert,PHI,TE,280.0,0.306271,0.043113,0,False,-10.000000,0.000000
21,00-0038979,Cedric Tillman,CLE,WR,280.0,0.275942,0.012784,1,True,28.000000,38.000000

In [391]:
top_25 = predictions.head(25)
simulate_betting(top_25, scorers)

{'bets': 25, 'hits': 15, 'hit_rate': 0.6, 'total_profit': 40.84, 'roi': 0.163}

,player_id,player_display_name,team,position,price,predicted_touchdown_probability,model_edge,tds,hit,profit,return
0,00-0032764,Derrick Henry,BAL,RB,-145.0,0.609973,0.018136,2,True,6.896552,16.896552
1,00-0039361,Bucky Irving,TB,RB,-140.0,0.600935,0.017602,1,True,7.142857,17.142857
2,00-0038542,Bijan Robinson,ATL,RB,-175.0,0.589403,-0.046961,1,True,5.714286,15.714286
3,00-0036555,Chuba Hubbard,CAR,RB,-105.0,0.582197,0.070001,1,True,9.523810,19.523810
4,00-0034844,Saquon Barkley,PHI,RB,-185.0,0.577634,-0.071488,1,True,5.405405,15.405405
5,00-0039040,De'Von Achane,MIA,RB,-140.0,0.574298,-0.009035,1,True,7.142857,17.142857
6,00-0036223,Jonathan Taylor,IND,RB,-180.0,0.552116,-0.090742,0,False,-10.000000,0.000000
7,00-0039139,Jahmyr Gibbs,DET,RB,-105.0,0.552014,0.039819,0,False,-10.000000,0.000000
8,00-0037840,Kyren Williams,LA,RB,-140.0,0.549713,-0.033620,1,True,7.142857,17.142857
9,00-0033553,James Conner,ARI,RB,-155.0,0.547825,-0.060018,1,True,6.451613,16.451613
10,00-0035700,Josh Jacobs,GB,RB,-160.0,0.547748,-0.067637,1,True,6.250000,16.250000
11,00-0038597,Chase Brown,CIN,RB,-150.0,0.544633,-0.055367,1,True,6.666667,16.666667
12,00-0036912,DeVonta Smith,PHI,WR,180.0,0.534621,0.177478,0,False,-10.000000,0.000000
13,00-0036900,Ja'Marr Chase,CIN,WR,-130.0,0.533280,-0.031938,0,False,-10.000000,0.000000
14,00-0037248,James Cook,BUF,RB,105.0,0.527458,0.039653,1,True,10.500000,20.500000
15,00-0031408,Mike Evans,TB,WR,110.0,0.515976,0.039785,0,False,-10.000000,0.000000
16,00-0039893,Brian Thomas Jr.,JAX,WR,130.0,0.514917,0.080135,1,True,13.000000,23.000000
17,00-0036158,J.K. Dobbins,DEN,RB,160.0,0.511576,0.126961,1,True,16.000000,26.000000
18,00-0033293,Aaron Jones,MIN,RB,165.0,0.505491,0.128132,1,True,16.500000,26.500000
19,00-0035676,A.J. Brown,PHI,WR,160.0,0.496160,0.111544,0,False,-10.000000,0.000000
20,00-0037744,Trey McBride,ARI,TE,200.0,0.495164,0.161831,0,False,-10.000000,0.000000
21,00-0039075,Puka Nacua,LA,WR,140.0,0.489732,0.073066,0,False,-10.000000,0.000000
22,00-0035659,Terry McLaurin,WAS,WR,130.0,0.485333,0.050550,0,False,-10.000000,0.000000
23,00-0039337,Malik Nabers,NYG,WR,150.0,0.484836,0.084836,0,False,-10.000000,0.000000
24,00-0030506,Travis Kelce,KC,TE,165.0,0.481134,0.103775,1,True,16.500000,26.500000

In [392]:
week_2 = pd.read_csv('data/predictions_week_2.csv')
week_2.sort_values('market_implied_prob', ascending=False).head(16)

,player_id,player_display_name,position,team,opponent_team,avg_avg_expected_yac,avg_avg_intended_air_yards,avg_avg_separation,avg_avg_time_to_los,avg_avg_yac_above_expectation,...,rush_matchup_value,pass_matchup_value,season,week,depth_chart_rank,predicted_touchdown_probability,merge_name,price,market_implied_prob,model_edge
0,00-0032764,Derrick Henry,RB,BAL,CLE,0.000000,0.000000,0.000000,1.602144,0.000000,...,0.857107,-0.420436,2025.0,1.0,-1.047657,0.603631,derrick henry,-205.0,0.672131,-0.068501
4,00-0035700,Josh Jacobs,RB,GB,WAS,0.000000,0.000000,0.000000,1.061422,0.000000,...,1.176405,-0.416520,2025.0,1.0,-1.047657,0.551611,josh jacobs,-200.0,0.666667,-0.115056
36,00-0033280,Christian McCaffrey,RB,SF,NO,0.000000,0.000000,0.000000,1.026647,0.000000,...,1.023502,4.842685,2025.0,1.0,-1.047657,0.432285,christian mccaffrey,-180.0,0.642857,-0.210572
2,00-0037840,Kyren Williams,RB,LA,TEN,0.000000,0.000000,0.000000,1.529216,0.000000,...,2.438944,-0.283749,2025.0,1.0,-1.047657,0.560748,kyren williams,-175.0,0.636364,-0.075616
8,00-0039139,Jahmyr Gibbs,RB,DET,CHI,0.000000,0.000000,0.000000,0.559129,0.000000,...,1.797469,1.709930,2025.0,1.0,-1.047657,0.544697,jahmyr gibbs,-170.0,0.629630,-0.084933
14,00-0039040,De'Von Achane,RB,MIA,NE,0.000000,0.000000,0.000000,0.806530,0.000000,...,0.655508,1.500415,2025.0,1.0,-1.047657,0.504077,devon achane,-155.0,0.607843,-0.103766
6,00-0038542,Bijan Robinson,RB,ATL,MIN,0.000000,0.000000,0.000000,1.740069,0.000000,...,2.344141,0.188136,2025.0,1.0,-1.047657,0.550620,bijan robinson,-155.0,0.607843,-0.057223
7,00-0033553,James Conner,RB,ARI,CAR,0.000000,0.000000,0.000000,0.998665,0.000000,...,0.498664,0.407134,2025.0,1.0,-1.047657,0.546881,james conner,-155.0,0.607843,-0.060962
5,00-0038597,Chase Brown,RB,CIN,JAX,0.000000,0.000000,0.000000,1.636657,0.000000,...,1.655122,1.710370,2025.0,1.0,-1.047657,0.551502,chase brown,-150.0,0.600000,-0.048498
1,00-0034844,Saquon Barkley,RB,PHI,KC,0.000000,0.000000,0.000000,1.777949,0.000000,...,0.141174,-0.418312,2025.0,1.0,-1.047657,0.580900,saquon barkley,-150.0,0.600000,-0.019100
18,00-0036223,Jonathan Taylor,RB,IND,DEN,0.000000,0.000000,0.000000,1.497618,0.000000,...,-0.199391,-0.142983,2025.0,1.0,-1.047657,0.492655,jonathan taylor,-145.0,0.591837,-0.099182
3,00-0037248,James Cook,RB,BUF,NYJ,0.000000,0.000000,0.000000,1.233845,0.000000,...,0.401638,0.112263,2025.0,1.0,-1.047657,0.560025,james cook,-140.0,0.583333,-0.023308
64,00-0035261,Tony Pollard,RB,TEN,LA,0.000000,0.000000,0.000000,1.084993,0.000000,...,-0.696283,-0.403625,2025.0,1.0,-1.047657,0.351788,tony pollard,-135.0,0.574468,-0.222681
23,00-0040666,Omarion Hampton,RB,LAC,LV,0.000000,0.000000,0.000000,1.625600,0.000000,...,0.915409,-0.421629,2025.0,1.0,-1.047657,0.475078,omarion hampton,-135.0,0.574468,-0.099390
37,00-0036900,Ja'Marr Chase,WR,CIN,JAX,1.171512,1.644332,0.957707,0.000000,2.896004,...,0.000000,0.107508,2025.0,1.0,-0.785505,0.427784,jamarr chase,-130.0,0.565217,-0.137433
25,00-0034857,Josh Allen,QB,BUF,NYJ,0.000000,0.000000,0.000000,0.000000,0.000000,...,1.384652,0.000000,2025.0,1.0,-0.534670,0.467899,josh allen,-125.0,0.555556,-0.087657

In [393]:
week_1_2024 = get_weekly_scorers(2024, 18)
week_2_2024 = get_weekly_scorers(2025, 1)

2024 done.
Downcasting floats.
2025 done.
Downcasting floats.

In [394]:
common_values = set(week_1_2024.player) & set(week_2_2024.player)
common_values

{'B.Irving',
 'B.Robinson',
 'C.Sutton',
 'D.Achane',
 'D.Henry',
 'J.Cook',
 'J.Jacobs',
 'J.Smith',
 'M.Harrison',
 'M.Penix',
 'N.Fant',
 'Z.Ertz'}